#!/bin/bash
echo "Start writing..."
{
echo "ORCHESTRATOR_PROVIDER=$ORCHESTRATOR_PROVIDER"
echo "ORCHESTRATOR_MODEL=$ORCHESTRATOR_MODEL"
echo "ORCHESTRATOR_API_KEY=$ORCHESTRATOR_API_KEY"
echo "CYPHER_PROVIDER=$CYPHER_PROVIDER"
echo "CYPHER_MODEL=$CYPHER_MODEL"
echo "CYPHER_API_KEY=$CYPHER_API_KEY"
echo "MEMGRAPH_HOST=$MEMGRAPH_HOST"
echo "MEMGRAPH_PORT=$MEMGRAPH_PORT"
echo "MEMGRAPH_HTTP_PORT=$MEMGRAPH_HTTP_PORT"
echo "LAB_PORT=$LAB_PORT"
echo "MEMGRAPH_BATCH_SIZE=$MEMGRAPH_BATCH_SIZE"
echo "TARGET_REPO_PATH=$TARGET_REPO_PATH"
echo "LOCAL_MODEL_ENDPOINT=$LOCAL_MODEL_ENDPOINT"
} > /cgr/.env
echo "Done."